#!/usr/bin/env node
/**
 * Setup script for agent-manager
 * Creates wrapper scripts in ~/.local/bin/ to make the CLI easily accessible
 */

import { existsSync, mkdirSync, writeFileSync, symlinkSync, unlinkSync, chmodSync } from 'fs';
import { dirname, join } from 'path';
import { homedir } from 'os';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const WRAPPER_TEMPLATE = `#!/bin/bash
# Wrapper script for agent-manager
# Automatically generated by setup script

NODE_PATH="{{NODE_PATH}}"

exec node "$NODE_PATH" "$@"
`;

async function setup() {
  const packageDir = join(__dirname, '..');
  const distPath = join(packageDir, 'dist', 'index.cjs');

  if (!existsSync(distPath)) {
    console.warn('⚠️  dist/index.cjs not found. Run "pnpm build" first.');
    return;
  }

  const localBin = join(homedir(), '.local', 'bin');
  if (!existsSync(localBin)) {
    mkdirSync(localBin, { recursive: true });
    console.log(`✓ Created ${localBin}`);
  }

  const wrapperPath = join(localBin, 'agent-manager');
  const wrapperContent = WRAPPER_TEMPLATE.replace('{{NODE_PATH}}', distPath);

  if (existsSync(wrapperPath)) {
    unlinkSync(wrapperPath);
  }

  writeFileSync(wrapperPath, wrapperContent);
  chmodSync(wrapperPath, '755');
  console.log(`✓ Created ${wrapperPath}`);

  const createSymlink = (name) => {
    const symlinkPath = join(localBin, name);

    if (existsSync(symlinkPath)) {
      unlinkSync(symlinkPath);
    }

    try {
      symlinkSync('agent-manager', symlinkPath);
      console.log(`✓ Created ${symlinkPath} -> agent-manager`);
    } catch (e) {
      console.warn(`⚠️  Could not create symlink ${symlinkPath}: ${e.message}`);
    }
  };

  createSymlink('agm');
  createSymlink('ag');

  console.log('\n✅ Setup complete! You can now use:');
  console.log('   agent-manager list');
  console.log('   agent-manager mcp list');
  console.log('   agm detect');
  console.log('\n💡 Make sure ~/.local/bin is in your PATH.');
}

setup().catch((e) => {
  console.error('Setup failed:', e.message);
  process.exit(1);
});
